# Generated by Django 2.0.7 on 2018-08-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20180810_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onepost',
            name='number_of_post',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='number_of_thread',
        ),
        migrations.AlterField(
            model_name='thread',
            name='number_of_OnePost',
            field=models.IntegerField(default=0),
        ),
    ]
